import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting database seeding...');

  // Create demo user for development/testing
  const demoUser = await prisma.user.upsert({
    where: { email: 'demo@example.com' },
    update: {
      name: 'Demo User',
      plan: 'PRO', // Give demo user PRO access for testing
    },
    create: {
      email: 'demo@example.com',
      name: 'Demo User',
      plan: 'PRO',
    },
  });

  console.log('✅ Demo user created/updated:', {
    id: demoUser.id,
    email: demoUser.email,
    name: demoUser.name,
    plan: demoUser.plan,
  });

  // Create additional test users if needed
  const basicUser = await prisma.user.upsert({
    where: { email: 'test@example.com' },
    update: {
      name: 'Test User',
      plan: 'BASIC',
    },
    create: {
      email: 'test@example.com',
      name: 'Test User', 
      plan: 'BASIC',
    },
  });

  console.log('✅ Test user created/updated:', {
    id: basicUser.id,
    email: basicUser.email,
    name: basicUser.name,
    plan: basicUser.plan,
  });

  // Seed modal data
  console.log('🌱 Seeding modal data...');
  
  const modalData = [
    // Original models
    {
      id: 'lm-studio',
      name: 'LM Studio',
      description: 'Local models via LM Studio',
      icon: 'cpu',
      color: 'purple',
      category: 'Local',
      isLocal: true,
      enabled: true,
    },
    {
      id: 'ollama',
      name: 'Ollama',
      description: 'Open source models',
      icon: 'zap',
      color: 'blue',
      category: 'Local',
      isLocal: true,
      enabled: true,
    },
    
    // Gemini models (Google)
    {
      id: 'gemini-2-0-flash',
      name: 'Gemini 2.0 Flash',
      description: 'Google\'s flagship model, known for speed and accuracy (and also web search!).',
      icon: 'sparkles',
      color: 'indigo',
      category: 'Google',
      isLocal: false,
      enabled: true,
    },
    {
      id: 'gemini-2-0-flash-lite',
      name: 'Gemini 2.0 Flash Lite',
      description: 'Similar to 2.0 Flash, but even faster.',
      icon: 'sparkles',
      color: 'indigo',
      category: 'Google',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'gemini-2-5-flash',
      name: 'Gemini 2.5 Flash',
      description: 'Google\'s state of the art fast model, known for speed and accuracy (and also web search!).',
      icon: 'sparkles',
      color: 'indigo',
      category: 'Google',
      isLocal: false,
      enabled: true,
    },
    {
      id: 'gemini-2-5-flash-thinking',
      name: 'Gemini 2.5 Flash (Thinking)',
      description: 'Google\'s state of the art fast model, now with support for "thinking".',
      icon: 'brain',
      color: 'indigo',
      category: 'Google',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'gemini-2-5-flash-lite',
      name: 'Gemini 2.5 Flash Lite',
      description: 'Gemini 2.5 Flash-Lite is a member of the Gemini 2.5 series of models.',
      icon: 'sparkles',
      color: 'indigo',
      category: 'Google',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'gemini-2-5-flash-lite-thinking',
      name: 'Gemini 2.5 Flash Lite (Thinking)',
      description: 'Gemini 2.5 Flash-Lite with thinking capabilities.',
      icon: 'brain',
      color: 'indigo',
      category: 'Google',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'gemini-2-5-pro',
      name: 'Gemini 2.5 Pro',
      description: 'Google\'s most advanced model, excelling at complex reasoning and problem-solving.',
      icon: 'crown',
      color: 'indigo',
      category: 'Google',
      isLocal: false,
      enabled: true,
    },
    {
      id: 'gemini-imagen-4',
      name: 'Gemini Imagen 4',
      description: 'Google\'s Imagen 4 creates high-quality, photorealistic images from text prompts.',
      icon: 'palette',
      color: 'indigo',
      category: 'Google',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'gemini-imagen-4-ultra',
      name: 'Gemini Imagen 4 Ultra',
      description: 'Google\'s Imagen 4 Ultra creates high-quality, photorealistic images from text prompts.',
      icon: 'palette',
      color: 'indigo',
      category: 'Google',
      isLocal: false,
      enabled: false,
    },
    
    // GPT models (OpenAI)
    {
      id: 'gpt-imagegen',
      name: 'GPT ImageGen',
      description: 'OpenAI\'s latest and greatest image generation model.',
      icon: 'palette',
      color: 'green',
      category: 'OpenAI',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'gpt-4o-mini',
      name: 'GPT-4o-mini',
      description: 'Like gpt-4o, but faster.',
      icon: 'zap',
      color: 'green',
      category: 'OpenAI',
      isLocal: false,
      enabled: true,
    },
    {
      id: 'gpt-4o',
      name: 'GPT-4o',
      description: 'OpenAI\'s flagship non-reasoning model.',
      icon: 'brain',
      color: 'green',
      category: 'OpenAI',
      isLocal: false,
      enabled: true,
    },
    {
      id: 'gpt-4-1',
      name: 'GPT-4.1',
      description: 'GPT-4.1 is a flagship model optimized for advanced instruction following.',
      icon: 'brain',
      color: 'green',
      category: 'OpenAI',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'gpt-4-1-mini',
      name: 'GPT-4.1 Mini',
      description: 'GPT-4.1 Mini delivering performance competitive with GPT-4o at lower latency.',
      icon: 'zap',
      color: 'green',
      category: 'OpenAI',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'gpt-4-1-nano',
      name: 'GPT-4.1 Nano',
      description: 'The fastest model in the GPT-4.1 series for low latency tasks.',
      icon: 'zap',
      color: 'green',
      category: 'OpenAI',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'gpt-5',
      name: 'GPT-5',
      description: 'OpenAI\'s latest flagship model.',
      icon: 'crown',
      color: 'green',
      category: 'OpenAI',
      isLocal: false,
      enabled: true,
    },
    {
      id: 'gpt-5-reasoning',
      name: 'GPT-5 (Reasoning)',
      description: 'OpenAI\'s latest flagship model with reasoning capabilities.',
      icon: 'brain',
      color: 'green',
      category: 'OpenAI',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'gpt-5-mini',
      name: 'GPT-5 mini',
      description: 'A lighter-weight GPT-5 variant optimized for speed while retaining strong reasoning.',
      icon: 'zap',
      color: 'green',
      category: 'OpenAI',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'gpt-5-nano',
      name: 'GPT-5 nano',
      description: 'An ultra-fast GPT-5 variant tuned for low-latency tasks.',
      icon: 'zap',
      color: 'green',
      category: 'OpenAI',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'o3-mini',
      name: 'o3-mini',
      description: 'A small, fast, super smart reasoning model.',
      icon: 'brain',
      color: 'green',
      category: 'OpenAI',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'o4-mini',
      name: 'o4-mini',
      description: 'A small, fast, even smarter reasoning model.',
      icon: 'brain',
      color: 'green',
      category: 'OpenAI',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'o3',
      name: 'o3',
      description: 'o3 is a well-rounded and powerful model across domains.',
      icon: 'brain',
      color: 'green',
      category: 'OpenAI',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'o3-pro',
      name: 'o3 Pro',
      description: 'The o3 series models are trained with reinforcement learning to think before they answer.',
      icon: 'crown',
      color: 'green',
      category: 'OpenAI',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'gpt-oss-20b',
      name: 'GPT OSS 20b',
      description: 'A medium-sized open-weight model from OpenAI suitable for general-purpose tasks.',
      icon: 'database',
      color: 'green',
      category: 'OpenAI',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'gpt-oss-120b',
      name: 'GPT OSS 120b',
      description: 'A large open-weight model from OpenAI.',
      icon: 'database',
      color: 'green',
      category: 'OpenAI',
      isLocal: false,
      enabled: false,
    },
    
    // Claude models (Anthropic)
    {
      id: 'claude-3-5-sonnet',
      name: 'Claude 3.5 Sonnet',
      description: 'Smart model for complex problems.',
      icon: 'message-square',
      color: 'orange',
      category: 'Anthropic',
      isLocal: false,
      enabled: true,
    },
    {
      id: 'claude-3-7-sonnet',
      name: 'Claude 3.7 Sonnet',
      description: 'The last gen model from Anthropic.',
      icon: 'message-square',
      color: 'orange',
      category: 'Anthropic',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'claude-3-7-sonnet-reasoning',
      name: 'Claude 3.7 Sonnet (Reasoning)',
      description: 'The last gen model from Anthropic (but you can make it think).',
      icon: 'brain',
      color: 'orange',
      category: 'Anthropic',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'claude-4-sonnet',
      name: 'Claude 4 Sonnet',
      description: 'The latest model from Anthropic.',
      icon: 'message-square',
      color: 'orange',
      category: 'Anthropic',
      isLocal: false,
      enabled: true,
    },
    {
      id: 'claude-4-sonnet-reasoning',
      name: 'Claude 4 Sonnet (Reasoning)',
      description: 'The latest model from Anthropic (but you can make it think).',
      icon: 'brain',
      color: 'orange',
      category: 'Anthropic',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'claude-4-opus',
      name: 'Claude 4 Opus',
      description: 'The latest and greatest from Anthropic.',
      icon: 'crown',
      color: 'orange',
      category: 'Anthropic',
      isLocal: false,
      enabled: false,
    },
    
    // Llama models (Meta)
    {
      id: 'llama-3-3-70b',
      name: 'Llama 3.3 70b',
      description: 'Industry-leading speed in an open source model.',
      icon: 'database',
      color: 'red',
      category: 'Meta',
      isLocal: false,
      enabled: true,
    },
    {
      id: 'llama-4-scout',
      name: 'Llama 4 Scout',
      description: 'Llama 4 Scout 17B Instruct is a mixture-of-experts (MoE) language model developed by Meta.',
      icon: 'database',
      color: 'red',
      category: 'Meta',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'llama-4-maverick',
      name: 'Llama 4 Maverick',
      description: 'Llama 4 Maverick 17B Instruct is a high-capacity multimodal language model from Meta.',
      icon: 'database',
      color: 'red',
      category: 'Meta',
      isLocal: false,
      enabled: false,
    },
    
    // DeepSeek models
    {
      id: 'deepseek-v3-fireworks',
      name: 'DeepSeek v3 (Fireworks)',
      description: 'DeepSeek\'s groundbreaking direct prediction model.',
      icon: 'brain',
      color: 'purple',
      category: 'DeepSeek',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'deepseek-v3-0324',
      name: 'DeepSeek v3 (0324)',
      description: 'DeepSeek V3, a 685B-parameter, mixture-of-experts model.',
      icon: 'brain',
      color: 'purple',
      category: 'DeepSeek',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'deepseek-r1-openrouter',
      name: 'DeepSeek R1 (OpenRouter)',
      description: 'The open source reasoning model that shook the whole industry.',
      icon: 'brain',
      color: 'purple',
      category: 'DeepSeek',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'deepseek-r1-0528',
      name: 'DeepSeek R1 (0528)',
      description: 'The open source reasoning model that shook the whole industry.',
      icon: 'brain',
      color: 'purple',
      category: 'DeepSeek',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'deepseek-r1-llama-distilled',
      name: 'DeepSeek R1 (Llama Distilled)',
      description: 'It\'s like normal R1, but WAY faster and slightly dumber.',
      icon: 'zap',
      color: 'purple',
      category: 'DeepSeek',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'deepseek-r1-qwen-distilled',
      name: 'DeepSeek R1 (Qwen Distilled)',
      description: 'Similar to the Llama distilled model, but distilled on Qwen 32b instead.',
      icon: 'zap',
      color: 'purple',
      category: 'DeepSeek',
      isLocal: false,
      enabled: false,
    },
    
    // Grok models (xAI)
    {
      id: 'grok-4',
      name: 'Grok 4',
      description: 'xAI\'s flagship model that breaks records on lots of benchmarks (allegedly).',
      icon: 'crown',
      color: 'blue',
      category: 'xAI',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'grok-3',
      name: 'Grok 3',
      description: 'xAI\'s flagship model that excels at data extraction, coding, and text summarization.',
      icon: 'brain',
      color: 'blue',
      category: 'xAI',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'grok-3-mini',
      name: 'Grok 3 Mini',
      description: 'A lightweight model that thinks before responding.',
      icon: 'brain',
      color: 'blue',
      category: 'xAI',
      isLocal: false,
      enabled: false,
    },
    
    // Qwen models
    {
      id: 'qwen-2-5-32b',
      name: 'Qwen 2.5 32b',
      description: 'The other really good open source model from China.',
      icon: 'database',
      color: 'yellow',
      category: 'Qwen',
      isLocal: false,
      enabled: true,
    },
    {
      id: 'qwen3-32b',
      name: 'Qwen3 32B',
      description: 'Qwen3-32B is a dense 32.8B parameter causal language model from the Qwen3 series.',
      icon: 'database',
      color: 'yellow',
      category: 'Qwen',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'qwen3-235b-thinking',
      name: 'Qwen3 235B (Thinking)',
      description: 'Qwen3-235B-A22B-Thinking is a high-performance MoE model optimized for complex reasoning.',
      icon: 'brain',
      color: 'yellow',
      category: 'Qwen',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'qwen3-235b',
      name: 'Qwen3 235B',
      description: 'Qwen3-235B is a multilingual, instruction-tuned mixture-of-experts language model.',
      icon: 'database',
      color: 'yellow',
      category: 'Qwen',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'qwen3-coder',
      name: 'Qwen3 Coder',
      description: 'Qwen3-Coder is a cutting-edge model from Alibaba that rivals o3, Deepseek, and even Kimi K2.',
      icon: 'brain',
      color: 'yellow',
      category: 'Qwen',
      isLocal: false,
      enabled: false,
    },
    
    // Other models
    {
      id: 'kimi-k2',
      name: 'Kimi K2',
      description: 'Kimi K2 is a large-scale MoE language model developed by Moonshot AI.',
      icon: 'brain',
      color: 'pink',
      category: 'Moonshot',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'glm-4-5',
      name: 'GLM 4.5',
      description: 'GLM-4.5 is an open-weight MoE model that competes with o3 and Claude 4.',
      icon: 'brain',
      color: 'teal',
      category: 'GLM',
      isLocal: false,
      enabled: false,
    },
    {
      id: 'glm-4-5-thinking',
      name: 'GLM 4.5 (Thinking)',
      description: 'GLM-4.5 with enhanced thinking capabilities.',
      icon: 'brain',
      color: 'teal',
      category: 'GLM',
      isLocal: false,
      enabled: false,
    }
  ];
  
  for (const modal of modalData) {
    await prisma.modal.upsert({
      where: { id: modal.id },
      update: modal,
      create: modal,
    });
  }

  console.log(`✅ Seeded ${modalData.length} modals`);
  console.log('✅ Seeding completed successfully!');
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error('❌ Seeding failed:', e);
    await prisma.$disconnect();
    process.exit(1);
  });